//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProtalEntities : DbContext
    {
        public ProtalEntities()
            : base("name=ProtalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<FM_CUST_GRP> FM_CUST_GRP { get; set; }
        public DbSet<FM_CUST_GRP_OBJ> FM_CUST_GRP_OBJ { get; set; }
        public DbSet<FM_CUST_POI> FM_CUST_POI { get; set; }
        public DbSet<FM_CUST_ROUTES> FM_CUST_ROUTES { get; set; }
        public DbSet<FM_CUST_USERS> FM_CUST_USERS { get; set; }
        public DbSet<FM_IMAGES> FM_IMAGES { get; set; }
        public DbSet<FM_LOG_ACTIONS> FM_LOG_ACTIONS { get; set; }
        public DbSet<FM_LOG_OBJECTS> FM_LOG_OBJECTS { get; set; }
        public DbSet<FM_OBJ_TYPES> FM_OBJ_TYPES { get; set; }
        public DbSet<FM_REPORTS> FM_REPORTS { get; set; }
        public DbSet<FM_TASK_LOG> FM_TASK_LOG { get; set; }
        public DbSet<FM_CUST_USERS_bkp> FM_CUST_USERS_bkp { get; set; }
        public DbSet<FM_POI_Web_mer_Ags_sfer> FM_POI_Web_mer_Ags_sfer { get; set; }
        public DbSet<FM_CUST_SETTINGS> FM_CUST_SETTINGS { get; set; }
        public DbSet<FM_LOG> FM_LOG { get; set; }
    }
}
