//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{

    public partial class FM_CUST_ROUTES
    {
        public int ROUTE_ID { get; set; }
        public string ROUTE_NAME { get; set; }
        public string ROUTE_DESC { get; set; }
        public byte[] ROUTE_DATA { get; set; }
    }
}
