//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_CUST_SETTINGS
    {
        public decimal CUST_ID { get; set; }
        public decimal ASSET_DISPNAME_ORD { get; set; }
        public decimal ASSET_FULLNAME_ORD { get; set; }
        public decimal ASSET_MSISDN_ORD { get; set; }
        public decimal ASSET_LBL_MINSCALE { get; set; }
        public decimal ASSET_LBL_MAXSCALE { get; set; }
        public decimal ASSET_SMALL_ICONSZ { get; set; }
        public decimal ASSET_LARGE_ICONSZ { get; set; }
        public decimal ASSET_ICON_MARGIN { get; set; }
        public decimal ASSET_SMALL_LABELSZ { get; set; }
        public decimal ASSET_LARGE_LABELSZ { get; set; }
    }
}
