//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_CUST_GRP
    {
        public FM_CUST_GRP()
        {
            this.FM_CUST_GRP_OBJ = new HashSet<FM_CUST_GRP_OBJ>();
        }
    
        public int GRP_ID { get; set; }
        public string GRP_NAME { get; set; }
        public Nullable<int> IMAGE_ID { get; set; }
    
        public virtual ICollection<FM_CUST_GRP_OBJ> FM_CUST_GRP_OBJ { get; set; }
        public virtual FM_IMAGES FM_IMAGES { get; set; }
    }
}
