//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_CUST_USERS
    {
        public FM_CUST_USERS()
        {
            FM_CUST_POI = new HashSet<FM_CUST_POI>();
        }
    
        public decimal USER_ID { get; set; }
        public Nullable<bool> USER_STATUS { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string USER_KEY { get; set; }
        public Nullable<System.DateTime> USER_KEY_DT { get; set; }
        public Nullable<bool> CUST_ADMIN { get; set; }
        public Nullable<bool> POI_ADMIN { get; set; }
        public string PREF_LANG { get; set; }
    
        public virtual ICollection<FM_CUST_POI> FM_CUST_POI { get; set; }
    }
}
