//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_CUST_POI
    {
        public FM_CUST_POI()
        {
            this.FM_CUST_GRP_OBJ = new HashSet<FM_CUST_GRP_OBJ>();
        }
    
        public int POI_ID { get; set; }
        public string POI_NAME { get; set; }
        public string POI_DESC { get; set; }
        public string SETTL_NAME { get; set; }
        public string ADDRESS { get; set; }
        public string HOUSE_NR { get; set; }
        public double GEOCODE_STATUS { get; set; }
        public Nullable<double> WM_X { get; set; }
        public Nullable<double> WM_Y { get; set; }
        public Nullable<double> HTRS_X { get; set; }
        public Nullable<double> HTRS_Y { get; set; }
    
        public virtual ICollection<FM_CUST_GRP_OBJ> FM_CUST_GRP_OBJ { get; set; }
    }
}
