//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_CUST_USERS_bkp
    {
        public decimal USER_ID { get; set; }
        public decimal USER_STATUS { get; set; }
        public decimal CUST_ID { get; set; }
        public string USER_NAME { get; set; }
        public string USER_PWD { get; set; }
        public string USER_KEY { get; set; }
        public Nullable<System.DateTime> USER_KEY_DT { get; set; }
        public decimal CUST_ADMIN { get; set; }
        public decimal ASSET_ADMIN { get; set; }
        public decimal POI_ADMIN { get; set; }
        public decimal TRACKING { get; set; }
        public decimal REPORTING { get; set; }
        public string PREF_LANG { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
