//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{

    public partial class FM_LOG_OBJECTS
    {
        public decimal OBJ_ID { get; set; }
        public string APP_NAME { get; set; }
        public string OBJ_NAME { get; set; }
        public string OBJ_DESC { get; set; }
    }
}
