//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;

    public partial class FM_LOG
    {
        public Nullable<decimal> LOG_ID { get; set; }
        public System.DateTime LOG_DTIME { get; set; }
        public Nullable<decimal> CUST_ID { get; set; }
        public Nullable<decimal> CUST_USER_ID { get; set; }
        public Nullable<decimal> CC_USER_ID { get; set; }
        public Nullable<decimal> OBJ_ID { get; set; }
        public Nullable<decimal> ACTION_ID { get; set; }
        public Nullable<decimal> ACTION_TAG { get; set; }
        public Nullable<decimal> ROW_PK_ID { get; set; }
        public string ROW_TAG { get; set; }
        public Nullable<decimal> RESULT { get; set; }
        public string SQL_CMD { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
