//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class FM_LOG_ACTIONS
    {
        public decimal ACTION_ID { get; set; }
        public string ACTION_NAME { get; set; }
        public string ACTION_DESC { get; set; }
    }
}
