//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{

    public partial class FM_OBJ_TYPES
    {
        public decimal OBJ_TYPE { get; set; }
        public string TYPE_DESC { get; set; }
    }
}
