//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;

    public partial class FM_POI_Web_mer_Ags_sfer
    {
        public int OBJECTID { get; set; }
        public Nullable<double> CUST_ID { get; set; }
        public string POI_NAME { get; set; }
        public string POI_DESC { get; set; }
        public string SETTL_NAME { get; set; }
        public string ADDRESS { get; set; }
        public Nullable<double> HOUSE_NR { get; set; }
        public string WORKING_HO { get; set; }
        public string PHONES { get; set; }
        public Nullable<double> GEOCODE_ST { get; set; }
        public Nullable<double> EOV_X { get; set; }
        public Nullable<double> EOV_Y { get; set; }
    }
}
