//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;

    public partial class FM_TASK_LOG
    {
        public decimal TASK_ID { get; set; }
        public System.DateTime TASK_LOG_DT { get; set; }
        public decimal CUST_ID { get; set; }
        public decimal CUST_USER_ID { get; set; }
        public decimal ASSET_ID { get; set; }
        public string ASSET_MSISDN { get; set; }
        public string TASK_MSG { get; set; }
        public Nullable<decimal> SMS_ID { get; set; }
        public Nullable<System.DateTime> TASK_TTC_DT { get; set; }
        public Nullable<System.DateTime> TASK_END_DT { get; set; }
        public Nullable<System.DateTime> TASK_MODIFIED_DT { get; set; }
        public decimal TASK_STATUS { get; set; }
        public System.Guid ROWID { get; set; }
    }
}
