//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI_GROUP_ACCESS_RIGHTS
    {
        public int ACCESS_RIGHT_ID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<short> SERVICE_ID { get; set; }
        public int POI_GROUP_ID { get; set; }
        public int MASTER_USER_ID { get; set; }
        public System.DateTime CREATED_DT { get; set; }
    }
}
