//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class POI_GROUPS
    {
        public POI_GROUPS()
        {
            this.POI_PLACES = new HashSet<POI_PLACES>();
        }
    
        public int POI_GROUP_ID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<int> CHILD_USER_ID { get; set; }
        public Nullable<short> SERVICE_ID { get; set; }
        public string POI_GROUP_NAME { get; set; }
        public short POI_GROUP_TYPE { get; set; }
        public System.DateTime CREATED_DT { get; set; }
        public Nullable<System.DateTime> MODIFIED_DT { get; set; }
        public Nullable<int> MODIFIED_BY { get; set; }
    
        public virtual ICollection<POI_PLACES> POI_PLACES { get; set; }
    }
}
