//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROUTE
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public int USER_ID { get; set; }
        public byte[] ROUTE { get; set; }
        public string OPTIMALROUTE { get; set; }
        public string RETURNTOSTART { get; set; }
    }
}
