//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arcgis.Directions.Orm
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ROUTING_POIS
    {
        public int POI_GROUP_ID { get; set; }
        public string POI_GROUP_NAME { get; set; }
        public short POI_GROUP_TYPE { get; set; }
        public Nullable<short> SERVICE_ID { get; set; }
        public int USER_ID { get; set; }
        public Nullable<decimal> POI_COUNT { get; set; }
    }
}
