//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spremi.
        /// </summary>
        internal static string ButtonSave {
            get {
                return ResourceManager.GetString("ButtonSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraživanje po mojim mjestima.
        /// </summary>
        internal static string CusPoiInputPlaceHolder {
            get {
                return ResourceManager.GetString("CusPoiInputPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraži Geokoder.
        /// </summary>
        internal static string DirectionsSearchGeocoder {
            get {
                return ResourceManager.GetString("DirectionsSearchGeocoder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GDi auto nadzor 7.9.1 | 2009 - 2017 GDi Convivo | Sva prava pridržana.
        /// </summary>
        internal static string FooterText {
            get {
                return ResourceManager.GetString("FooterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moja mjesta.
        /// </summary>
        internal static string PoiGroupsTab {
            get {
                return ResourceManager.GetString("PoiGroupsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unesite ime route koju spremate.
        /// </summary>
        internal static string SavbeInputPlaceHolder {
            get {
                return ResourceManager.GetString("SavbeInputPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Route.
        /// </summary>
        internal static string SaveRouteTab {
            get {
                return ResourceManager.GetString("SaveRouteTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretraživanje ruta.
        /// </summary>
        internal static string SearchInputPlaceHolder {
            get {
                return ResourceManager.GetString("SearchInputPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akcija.
        /// </summary>
        internal static string TableColAction {
            get {
                return ResourceManager.GetString("TableColAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        internal static string TableColDate {
            get {
                return ResourceManager.GetString("TableColDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv.
        /// </summary>
        internal static string TableColName {
            get {
                return ResourceManager.GetString("TableColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rutiranje.
        /// </summary>
        internal static string TabRouting {
            get {
                return ResourceManager.GetString("TabRouting", resourceCulture);
            }
        }
    }
}
